apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  namespace: cmm707-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
      - name: agent-service
        image: agent-service:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "3600"]  # 👈 override CMD to keep container alive
        
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: cmm707-microservices
spec:
  selector:
    app: agent-service
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
  type: NodePort 